name: Generate Datas

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Udith-creates
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step 2: Push the generated files to the output branch
      - name: Push Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
